name: Update RSS

on:
  schedule:
    - cron: "0 * * * *"   # tiap 1 jam sekali
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm start
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/feed.xml
          git commit -m "Update feed"
          git push
